/*
Copyright 2020 DevSpace Technologies Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/loft-sh/kiosk/pkg/apis/config/v1alpha1"
	scheme "github.com/loft-sh/kiosk/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AccountQuotasGetter has a method to return a AccountQuotaInterface.
// A group's client should implement this interface.
type AccountQuotasGetter interface {
	AccountQuotas() AccountQuotaInterface
}

// AccountQuotaInterface has methods to work with AccountQuota resources.
type AccountQuotaInterface interface {
	Create(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.CreateOptions) (*v1alpha1.AccountQuota, error)
	Update(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.UpdateOptions) (*v1alpha1.AccountQuota, error)
	UpdateStatus(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.UpdateOptions) (*v1alpha1.AccountQuota, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AccountQuota, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AccountQuotaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccountQuota, err error)
	AccountQuotaExpansion
}

// accountQuotas implements AccountQuotaInterface
type accountQuotas struct {
	client rest.Interface
}

// newAccountQuotas returns a AccountQuotas
func newAccountQuotas(c *ConfigV1alpha1Client) *accountQuotas {
	return &accountQuotas{
		client: c.RESTClient(),
	}
}

// Get takes name of the accountQuota, and returns the corresponding accountQuota object, and an error if there is any.
func (c *accountQuotas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccountQuota, err error) {
	result = &v1alpha1.AccountQuota{}
	err = c.client.Get().
		Resource("accountquotas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AccountQuotas that match those selectors.
func (c *accountQuotas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccountQuotaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AccountQuotaList{}
	err = c.client.Get().
		Resource("accountquotas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested accountQuotas.
func (c *accountQuotas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("accountquotas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a accountQuota and creates it.  Returns the server's representation of the accountQuota, and an error, if there is any.
func (c *accountQuotas) Create(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.CreateOptions) (result *v1alpha1.AccountQuota, err error) {
	result = &v1alpha1.AccountQuota{}
	err = c.client.Post().
		Resource("accountquotas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accountQuota).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a accountQuota and updates it. Returns the server's representation of the accountQuota, and an error, if there is any.
func (c *accountQuotas) Update(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.UpdateOptions) (result *v1alpha1.AccountQuota, err error) {
	result = &v1alpha1.AccountQuota{}
	err = c.client.Put().
		Resource("accountquotas").
		Name(accountQuota.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accountQuota).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *accountQuotas) UpdateStatus(ctx context.Context, accountQuota *v1alpha1.AccountQuota, opts v1.UpdateOptions) (result *v1alpha1.AccountQuota, err error) {
	result = &v1alpha1.AccountQuota{}
	err = c.client.Put().
		Resource("accountquotas").
		Name(accountQuota.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(accountQuota).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the accountQuota and deletes it. Returns an error if one occurs.
func (c *accountQuotas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("accountquotas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *accountQuotas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("accountquotas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched accountQuota.
func (c *accountQuotas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccountQuota, err error) {
	result = &v1alpha1.AccountQuota{}
	err = c.client.Patch(pt).
		Resource("accountquotas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
