/*
Copyright 2020 DevSpace Technologies Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kiosk-sh/kiosk/pkg/apis/tenancy/v1alpha1"
	scheme "github.com/kiosk-sh/kiosk/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AccountsGetter has a method to return a AccountInterface.
// A group's client should implement this interface.
type AccountsGetter interface {
	Accounts() AccountInterface
}

// AccountInterface has methods to work with Account resources.
type AccountInterface interface {
	Create(*v1alpha1.Account) (*v1alpha1.Account, error)
	Update(*v1alpha1.Account) (*v1alpha1.Account, error)
	UpdateStatus(*v1alpha1.Account) (*v1alpha1.Account, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Account, error)
	List(opts v1.ListOptions) (*v1alpha1.AccountList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Account, err error)
	AccountExpansion
}

// accounts implements AccountInterface
type accounts struct {
	client rest.Interface
}

// newAccounts returns a Accounts
func newAccounts(c *TenancyV1alpha1Client) *accounts {
	return &accounts{
		client: c.RESTClient(),
	}
}

// Get takes name of the account, and returns the corresponding account object, and an error if there is any.
func (c *accounts) Get(name string, options v1.GetOptions) (result *v1alpha1.Account, err error) {
	result = &v1alpha1.Account{}
	err = c.client.Get().
		Resource("accounts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Accounts that match those selectors.
func (c *accounts) List(opts v1.ListOptions) (result *v1alpha1.AccountList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AccountList{}
	err = c.client.Get().
		Resource("accounts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested accounts.
func (c *accounts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("accounts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a account and creates it.  Returns the server's representation of the account, and an error, if there is any.
func (c *accounts) Create(account *v1alpha1.Account) (result *v1alpha1.Account, err error) {
	result = &v1alpha1.Account{}
	err = c.client.Post().
		Resource("accounts").
		Body(account).
		Do().
		Into(result)
	return
}

// Update takes the representation of a account and updates it. Returns the server's representation of the account, and an error, if there is any.
func (c *accounts) Update(account *v1alpha1.Account) (result *v1alpha1.Account, err error) {
	result = &v1alpha1.Account{}
	err = c.client.Put().
		Resource("accounts").
		Name(account.Name).
		Body(account).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *accounts) UpdateStatus(account *v1alpha1.Account) (result *v1alpha1.Account, err error) {
	result = &v1alpha1.Account{}
	err = c.client.Put().
		Resource("accounts").
		Name(account.Name).
		SubResource("status").
		Body(account).
		Do().
		Into(result)
	return
}

// Delete takes name of the account and deletes it. Returns an error if one occurs.
func (c *accounts) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("accounts").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *accounts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("accounts").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched account.
func (c *accounts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Account, err error) {
	result = &v1alpha1.Account{}
	err = c.client.Patch(pt).
		Resource("accounts").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
