/*
Copyright 2020 DevSpace Technologies Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kiosk-sh/kiosk/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccountQuotas implements AccountQuotaInterface
type FakeAccountQuotas struct {
	Fake *FakeConfigV1alpha1
}

var accountquotasResource = schema.GroupVersionResource{Group: "config.kiosk.sh", Version: "v1alpha1", Resource: "accountquotas"}

var accountquotasKind = schema.GroupVersionKind{Group: "config.kiosk.sh", Version: "v1alpha1", Kind: "AccountQuota"}

// Get takes name of the accountQuota, and returns the corresponding accountQuota object, and an error if there is any.
func (c *FakeAccountQuotas) Get(name string, options v1.GetOptions) (result *v1alpha1.AccountQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(accountquotasResource, name), &v1alpha1.AccountQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountQuota), err
}

// List takes label and field selectors, and returns the list of AccountQuotas that match those selectors.
func (c *FakeAccountQuotas) List(opts v1.ListOptions) (result *v1alpha1.AccountQuotaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(accountquotasResource, accountquotasKind, opts), &v1alpha1.AccountQuotaList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AccountQuotaList{ListMeta: obj.(*v1alpha1.AccountQuotaList).ListMeta}
	for _, item := range obj.(*v1alpha1.AccountQuotaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accountQuotas.
func (c *FakeAccountQuotas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(accountquotasResource, opts))
}

// Create takes the representation of a accountQuota and creates it.  Returns the server's representation of the accountQuota, and an error, if there is any.
func (c *FakeAccountQuotas) Create(accountQuota *v1alpha1.AccountQuota) (result *v1alpha1.AccountQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(accountquotasResource, accountQuota), &v1alpha1.AccountQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountQuota), err
}

// Update takes the representation of a accountQuota and updates it. Returns the server's representation of the accountQuota, and an error, if there is any.
func (c *FakeAccountQuotas) Update(accountQuota *v1alpha1.AccountQuota) (result *v1alpha1.AccountQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(accountquotasResource, accountQuota), &v1alpha1.AccountQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountQuota), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAccountQuotas) UpdateStatus(accountQuota *v1alpha1.AccountQuota) (*v1alpha1.AccountQuota, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(accountquotasResource, "status", accountQuota), &v1alpha1.AccountQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountQuota), err
}

// Delete takes name of the accountQuota and deletes it. Returns an error if one occurs.
func (c *FakeAccountQuotas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(accountquotasResource, name), &v1alpha1.AccountQuota{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccountQuotas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(accountquotasResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AccountQuotaList{})
	return err
}

// Patch applies the patch and returns the patched accountQuota.
func (c *FakeAccountQuotas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AccountQuota, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(accountquotasResource, name, pt, data, subresources...), &v1alpha1.AccountQuota{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccountQuota), err
}
